import { chooseOption } from "./fixtures";
import AxeBuilder from "@axe-core/playwright";
import { test, expect } from "./fixtures";

test("UBL validado, estado local y exportación conservados sin entrega remota", async ({ page, rpc, backend }) => {
  await rpc("demo.load");
  const invoices = await rpc<{ items: { id: string; full_number: string }[] }>("documents.list", { status: "issued" });
  const original = invoices.items[0];
  await page.goto("/");
  await page.getByRole("button", { name: "Configuración", exact: true }).click();
  await page.getByRole("button", { name: "Factura electrónica B2B", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Factura electrónica entre empresas" })).toBeVisible();
  await chooseOption(page.getByRole("combobox", { name: "Factura emitida", exact: true }), original.id);
  await page.getByLabel("El destinatario actúa como empresa o profesional en esta operación").check();
  await page.getByRole("button", { name: "Preparar y validar UBL" }).click();
  const detail = page.getByRole("dialog", { name: "Factura electrónica " + original.full_number });
  await expect(detail).toBeVisible();
  await expect(detail.getByText("Documento de prueba sin validez fiscal.", { exact: true })).toBeVisible();
  await expect(detail.getByText(/validación local superada/)).toBeVisible();
  await detail.getByRole("button", { name: "Registrar estado" }).click();
  await detail.getByLabel("Justificante o evidencia").fill("Aceptación sintética para prueba local de interfaz");
  await detail.getByRole("button", { name: "Conservar estado" }).click();
  await expect(detail.getByText("Aceptación sintética para prueba local de interfaz", { exact: true })).toBeVisible();
  const downloadEvent = page.waitForEvent("download");
  await detail.getByRole("button", { name: "Guardar XML UBL" }).click();
  const download = await downloadEvent;
  expect(download.suggestedFilename()).toMatch(/^PRUEBA-.*\.ubl\.xml$/);
  const stream = await download.createReadStream();
  const pieces: Buffer[] = [];
  for await (const piece of stream!) pieces.push(Buffer.from(piece));
  const xml = Buffer.concat(pieces).toString("utf8");
  expect(xml).toContain("urn:oasis:names:specification:ubl:schema:xsd:Invoice-2");
  expect(xml).toContain("DOCUMENTO DE PRUEBA SIN VALIDEZ FISCAL");
  await expect(detail.getByText("Archivo exportado", { exact: true })).toBeVisible();
  await detail.getByRole("button", { name: "Cerrar ventana" }).click();
  const axe = await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa", "wcag22aa"]).analyze();
  expect(axe.violations, JSON.stringify(axe.violations.map(item => ({ id: item.id, nodes: item.nodes.map(node => node.target) })))).toEqual([]);
  const list = await rpc<{ items: { id: string }[] }>("b2b.list");
  expect(list.items).toHaveLength(1);
  await backend.restart();
  const stored = await rpc<{ remote_delivered: boolean; commercial_state: string; xml: string }>("b2b.get", { identifier: list.items[0].id });
  expect(stored.remote_delivered).toBe(false);
  expect(stored.commercial_state).toBe("accepted");
  expect(stored.xml).toBe(xml);
});
